### ISSUE TITLE
Add same Group consult but with different location

### ISSUE THREAD

**Issue by Rishi5154** [AY2021S1-CS2103T-F11-1/tp#173]
**Bug: Add Group Consults with the same time & date but different location, with no exception thrown**

Spent quite some time trying to fix this but had issues doing so.
Largely was down to the difficulty in fixing the test cases at `UniqueConsultListTest` due to a unclear error message, would be better if someone else can take this up instead.

<img width="899" alt="Screenshot 2020-11-07 at 3 12 51 PM" src="https://user-images.githubusercontent.com/49579253/98434553-b5008880-210b-11eb-909d-c4ad9c609ece.png">

**Comment by kwannoel** [comment]
https://github.com/AY2021S1-CS2103T-F11-1/tp/issues/178
