### ISSUE TITLE
Investigate and apply fixes for consultations and attendance

### ISSUE THREAD

**Issue by kwannoel** [AY2021S1-CS2103T-F11-1/tp#178]

**Comment by kwannoel** [comment]
https://github.com/AY2021S1-CS2103T-F11-1/tp/pull/165/files#r519247879

**Comment by kwannoel** [comment]
https://github.com/AY2021S1-CS2103T-F11-1/tp/pull/172#discussion_r519247480

**Comment by chrisgzf** [comment]
Fixed, closing.
