### ISSUE TITLE
View student attendance

### ISSUE THREAD

**Issue by kwannoel** [AY2021S1-CS2103T-F11-1/tp#7]
- [ ] Show all student attendance in a table for a given `module` and `semester`

E.g.
| Student name | Matric no. | Week 1 | Week 2 | Week 3 | ... |
| - | - | - | - | - | - |
| Jason | A100100H | 1 | 1 | 1 | |
| Jack | A200200H | 1 | 0 | 1 | |
| Jamie | A200200H | 0 | 1 | 1 | |

**Comment by chrisgzf** [comment]
Superseded by #72
